### PR TITLE
Add OpenBSD support

### PR DESCRIPTION
**Pull request by jasperla**
With these changes I can run rp++ on OpenBSD.

### CODE REVIEW

**Comment by jasperla** [comment]
The reason I removed the `abort()` call was because it seems the original intent was to return the "unknown type" message all along. Otherwise either the `abort()` or "unknown type" message should be removed as not both could be executed. I figured it's more helpful to print an informative message instead of crashing :-)

**Comment by 0vercl0k** [comment]
Haha yeah it looks a bit funky - I think the reason is that I needed to
return an `std::string` to make the compiler happy but wanted to abort at
runtime. The goal was to be noisy about processing files w/ segments that I
didn't know about so that folks can let me know.

Do you mind reverting that bit? I don't think it's a big deal but ideally
I'd like to keep the same behavior as before :)

Cheers

**Comment by 0vercl0k** [comment]
Thank you again 🙏!

**Comment by jasperla** [comment]
Thanks for the merge and the `abort()` touch-up!

**Pull request merged**
